<Project>

  <PropertyGroup>
    <!-- See https://www.nuget.org/packages/JetBrains.ReSharper.SDK -->
    <!-- Keep in sync with ProductVersion in gradle.properties -->
    <SdkVersion>2024.1</SdkVersion>

    <Title>Guid Generator</Title>
    <Description>It's a plugin to generate guid in a comfortable way</Description>

    <Authors>Denys Semko</Authors>
    <Copyright>Copyright $([System.DateTime]::Now.Year) Maintainers of GuidGenerator</Copyright>
    <PackageTags>resharper plugin</PackageTags>

    <PackageProjectUrl></PackageProjectUrl>
    <PackageLicenseUrl></PackageLicenseUrl>
    <PackageIconUrl></PackageIconUrl>
  </PropertyGroup>

</Project>
