<Project>

<PropertyGroup>
    <!-- See https://www.nuget.org/packages/JetBrains.ReSharper.SDK -->
    <!-- Keep in sync with ProductVersion in gradle.properties -->
    <SdkVersion>2025.3.0.3</SdkVersion>

    <Title>Guid Generator</Title>
    <Description>It's a plugin to generate guid in a comfortable way</Description>

    <Authors>Denys Semko</Authors>
    <Copyright>Copyright $([System.DateTime]::Now.Year) Maintainers of GuidGenerator</Copyright>
    <PackageTags>resharper plugin</PackageTags>

    <PackageProjectUrl>https://github.com/DenysSemko/GuidGenerator</PackageProjectUrl>
    <PackageLicenseUrl>https://github.com/DenysSemko/GuidGenerator/blob/main/LICENSE</PackageLicenseUrl>
    <PackageIconUrl></PackageIconUrl>
</PropertyGroup>

</Project>
